CREATE TABLE HCO (
    HCO_ID INT IDENTITY(1,1) PRIMARY KEY,
    HCO_Name VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(50),
    State VARCHAR(50),
    ZipCode VARCHAR(10)
);

CREATE TABLE HCP (
    HCP_ID INT IDENTITY(1,1) PRIMARY KEY,
    HCO_ID INT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Phone VARCHAR(15),
    CONSTRAINT FK_HCP_HCO FOREIGN KEY (HCO_ID) REFERENCES HCO(HCO_ID)
);

CREATE TABLE HCP_Specialty (
    HCP_ID INT PRIMARY KEY,  -- one specialty per HCP
    Specialty VARCHAR(100) NOT NULL,
    SubSpecialty VARCHAR(100),
    CONSTRAINT FK_HCPSpecialty_HCP FOREIGN KEY (HCP_ID) REFERENCES HCP(HCP_ID)
);

CREATE TABLE HCP_Address (
    HCP_ID INT PRIMARY KEY,  -- one address per HCP
    HCO_ID INT NOT NULL,     -- also link back to the HCO record
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(50),
    State VARCHAR(50),
    ZipCode VARCHAR(10),
    CONSTRAINT FK_HCPAddress_HCP FOREIGN KEY (HCP_ID) REFERENCES HCP(HCP_ID),
    CONSTRAINT FK_HCPAddress_HCO FOREIGN KEY (HCO_ID) REFERENCES HCO(HCO_ID)
);


